# Generated by Django 6.0.8 on 2026-09-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0047_mve_statuses'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='l1portalentry',
            new_name='playbooks_l_organiz_92d5c5_idx',
            old_name='playbooks_l1_organiz_7de8ec_idx',
        ),
        migrations.RenameIndex(
            model_name='l1portalentry',
            new_name='playbooks_l_url_tok_5d1080_idx',
            old_name='playbooks_l1_url_tok_b4d8d6_idx',
        ),
        migrations.RenameIndex(
            model_name='mvedraft',
            new_name='playbooks_m_organiz_c102ce_idx',
            old_name='playbooks_mv_organiz_0d6f4e_idx',
        ),
        migrations.RenameIndex(
            model_name='mvedraft',
            new_name='playbooks_m_organiz_149b57_idx',
            old_name='playbooks_mv_organiz_58d7f7_idx',
        ),
        migrations.RenameIndex(
            model_name='mveedge',
            new_name='playbooks_m_draft_i_8ece26_idx',
            old_name='playbooks_mv_draft_i_2a8f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='mvenode',
            new_name='playbooks_m_draft_i_537d23_idx',
            old_name='playbooks_mv_draft_i_2a6cb7_idx',
        ),
        migrations.RenameIndex(
            model_name='mvenode',
            new_name='playbooks_m_draft_i_c81379_idx',
            old_name='playbooks_mv_draft_i_29f4d9_idx',
        ),
        migrations.RenameIndex(
            model_name='mvevalidationrun',
            new_name='playbooks_m_draft_i_bc9465_idx',
            old_name='playbooks_mv_draft_i_e402e0_idx',
        ),
        migrations.RenameIndex(
            model_name='mvevalidationrun',
            new_name='playbooks_m_status_93ebb8_idx',
            old_name='playbooks_mv_status_a04b66_idx',
        ),
    ]
