# Generated by Django 6.0.8 on 2026-09-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playbooks', '0048_rename_playbooks_l1_organiz_7de8ec_idx_playbooks_l_organiz_92d5c5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionplaybook',
            name='robustness_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1: Ephemeral (IP, Domain, Hash)'), (2, 'Level 2: Implementation / Attacker-Controlled'), (3, 'Level 3: System-Constrained Interaction (LOLBin)'), (4, 'Level 4: Low-Variance Behaviors / Core Sometimes'), (5, 'Level 5: Invariant Behaviors / Core to Technique')], help_text='How easy is this detection to evade?', null=True),
        ),
    ]
